---
# vim: set expandtab

- include: repo_rpm.yml
  when: ansible_os_family == 'RedHat'

- name: install JRE
  yum:
    name: java
    state: latest

- name: Install LogStash package
  yum:
    name: logstash
    state: present

- name: Ensure LogStash is stopped and enabled at boot
  service:
    name: logstash
    state: stopped
    enabled: yes

- name: set LogStash configuration files.
  template:
    src: "logstash/{{ item }}.j2"
    dest: "/etc/logstash/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 300_output_elastic.conf
  notify: restart_logstash


- name: set LogStash configuration file for local syslog
  template:
    src: "logstash/010_input_local_syslog.conf.j2"
    dest: "/etc/logstash/conf.d/010_input_local_syslog.conf"
    owner: root
    group: root
    mode: 0644
  when: ls_local_syslog_enable
  notify: restart_logstash

- name: set LogStash configuration file for Beats
  template:
    src: "logstash/011_input_beats.conf.j2"
    dest: "/etc/logstash/conf.d/011_input_beats.conf"
    owner: root
    group: root
    mode: 0644
  when: "'logstash-input-beats' in ls_install_plugins"
  notify: restart_logstash

- name: set Logstash filters.
  copy:
    src: "logstash/filters/{{ item }}"
    dest: "/etc/logstash/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 201_filter_syslog.conf
    - 210_filter_apache.conf
    - 211_filter_nginx.conf
  notify: restart_logstash


### Plugins
- name: find logstash-plugin executable
  find:
    paths: '/usr'
    recurse: yes
    patterns: 'logstash-plugin'
    use_regex: no
  register: find_logstash_plugin

- set_fact:
    logstash_plugin: "{{ find_logstash_plugin.files[0].path }}"
  when: find_logstash_plugin.matched == 1
 
- block:

  - name: Get list of installed plugins
    command: >
      {{ logstash_plugin }} list
#     chdir=/opt/logstash
    register: logstash_plugins_list
    changed_when: false
  
  - name: Install configured plugins
    command: >
      {{ logstash_plugin }} install {{ item }}
#     chdir=/opt/logstash
    with_items: "{{ ls_install_plugins }}"
    when: "item not in logstash_plugins_list.stdout"
    notify: restart_logstash

  when: find_logstash_plugin.matched == 1

# todo: config de logstash

